---
- hosts: master
  tasks:
   - name: restart mysql server
     when: ansible_distribution_major_version == "7"
     systemd:
      name: mysql
      state: restarted
      daemon_reload: yes 

   - name: sleep 5's
     shell: sleep 5    

- hosts: sysbench
  tasks:
   - name: cleanup database table
     shell: /usr/local/sysbench/bin/sysbench --mysql-host={{ mysql_host }} --mysql-port={{ mysql_port }} --mysql-user={{ mysql_user }} --mysql-password={{ mysql_password }} --tables={{ mysql_tables }} --table_size={{ mysql_table_rows }} --mysql-db=tempdb oltp_insert cleanup
     