---
- hosts: master
  vars:
   variable_name: innodb_log_file_size
   variable_value: 16M

  tasks:
   - name: config /etc/my.cnf
     template:
      src: templates/my.cnf_innodb_log_file_size
      dest: /etc/my.cnf

   - name: restart mysql server
     when: ansible_distribution_major_version == "7"
     systemd:
      name: mysql
      state: restarted
      daemon_reload: yes 

- hosts: sysbench
  vars:
   variable_name: innodb_log_file_size
   variable_value: 16M

  tasks:
   - name: sleep 5's
     shell: sleep 5    

   - name: run sysbench
     when: (benchtypes.find(item.benchtype) != -1 and item.threads <=sysbench_max_threads and item.threads >=sysbench_min_threads and item.threads % sysbench_thread_setp == 0 ) or ( benchtypes.find(item.benchtype) != -1 and item.threads==1 ) 
     loop: "{{benchs}}"