---
- hosts: master
  vars:
   variable_name: innodb_flush_log_at_trx_commit
   variable_value: 0

  tasks:
   - name: config /etc/my.cnf
     template:
      src: templates/my.cnf_innodb_flush_log_at_trx_commit
      dest: /etc/my.cnf

   - name: restart mysql server
     when: ansible_distribution_major_version == "7"
     systemd:
      name: mysql
      state: restarted
      daemon_reload: yes 

- hosts: sysbench
  vars:
   variable_name: innodb_flush_log_at_trx_commit
   variable_value: 0

  tasks:
   - name: sleep 5's
     shell: sleep 5    

   - name: run sysbench
     when: (benchtypes.find(item.benchtype) != -1 and item.threads <=sysbench_max_threads and item.threads >=sysbench_min_threads and item.threads % sysbench_thread_setp == 0 ) or ( benchtypes.find(item.benchtype) != -1 and item.threads==1 ) 
     shell: /usr/local/sysbench/bin/sysbench --mysql-host={{ mysql_host }} --mysql-port={{ mysql_port }} --mysql-user={{ mysql_user }} --mysql-password={{ mysql_password }} --tables={{ mysql_tables }} --table_size={{ mysql_table_rows }} --mysql-db=tempdb --time={{time}} --threads={{item.threads}} {{item.benchtype}} run > /tmp/gogo/{{item.benchtype}}#{{variable_name}}#{{variable_value}}#{{item.threads}}.log
     loop: "{{benchs}}"