---
- hosts: master
  tasks:
   - name: restart mysql server
     when: ansible_distribution_major_version == "7"
     systemd:
      name: mysql
      state: restarted
      daemon_reload: yes 

- hosts: sysbench
  vars_files:
   - ../benchs.yaml
  vars:
   variable_name: tuning
   variable_value: 0
   sysbench_thread_setp: 8
   sysbench_max_threads: 16
   sysbench_min_threads: 8

  tasks:
   - name: sleep 5's
     shell: sleep 5    

   - name: run sysbench
     when: (item.benchtype =='oltp_read_write' and item.threads <=sysbench_max_threads and item.threads >=sysbench_min_threads and item.threads % sysbench_thread_setp == 0 ) or ( item.benchtype =='oltp_read_write' and item.threads==1 )  
     shell: /usr/local/sysbench/bin/sysbench --mysql-host={{ mysql_host }} --mysql-port={{ mysql_port }} --mysql-user={{ mysql_user }} --mysql-password={{ mysql_password }} --tables={{ mysql_tables }} --table_size={{ mysql_table_rows }} --mysql-db=tempdb --time={{time}} --threads={{item.threads}} {{item.benchtype}} run > /tmp/gogo/{{item.benchtype}}#{{variable_name}}#{{variable_value}}#{{item.threads}}.log
     loop: "{{benchs}}"